### PR TITLE
source.css without watermark

### PR DESCRIPTION
**Pull request by xfr4g6er**
Hi i am not sure if this will work but i try to edit source to remove watermark cause so many people think Material next to discord isn't nice so if you can remove this material next to Discord please remove it.

Thanks

### CODE REVIEW

**Comment by CapnKitten** [comment]
This is the first I'm hearing of it. Who has said it isn't nice bedsides you?

**Comment by xfr4g6er** [comment]
Lot of guys which i ask said they don't like that Material next to Discord

**Comment by CapnKitten** [comment]
Again, this is the first I'm hearing of it. If someone else didn't like enough to the point of wanting it changed, they would've made an issue here, DMed me on Discord, or even just a comment on betterdiscordlibrary.com; the only places where I am active and respond to people's issues and comments.

If you don't like it, you clearly know enough css to make an edit on your local file.

**Comment by xfr4g6er** [comment]
Ok thanks 👍

**Pull request closed without merging**
