### PR TITLE
update buttons to be more accurate

### PR DESCRIPTION
**Pull request by KTibow**

### CODE REVIEW

**Comment by KTibow** [comment]
@CapnKitten what command do you use to compile it? i get an error about importing css

**Comment by KTibow** [comment]
nvm you fixed some of the stuff
also it looks like you changed the chat color but didn't add it to the material you background theming css?

**Comment by CapnKitten** [comment]
> @CapnKitten what command do you use to compile it? i get an error about importing css

What's the specific error?

> nvm you fixed some of the stuff also it looks like you changed the chat color but didn't add it to the material you background theming css?

The chat color was changed to `--main-color` a while ago. I just decided to comment out the chat color variable in the Material You file instead of removing it in case most people didn't like the change.

**Comment by KTibow** [comment]
restarted discord and things are normal
and i think i was using the wrong command or something for the css, `npx sass src:css/` works

**Comment by CapnKitten** [comment]
I use Dart Sass and have it watch for any sass changes in the themes folder.

**Pull request closed without merging**
